language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - cmake
      - libopenmpi-dev
      - openmpi-bin

before_install:
 - mkdir -p "$HOME/bin"
 - if [[ ${CMAKE_VERSION} ]]; then wget --no-check-certificate -qO- http://www.cmake.org/files/v${CMAKE_VERSION:0:3}/cmake-${CMAKE_VERSION}.tar.gz | tar -xz && ln -s $PWD/cmake-${CMAKE_VERSION}/bin/cmake "$HOME/bin/cmake"; fi
 - if [[ ${COVERAGE}  ]]; then pip install --user codecov; fi

env: #maybe add mpich later
  global:
    - CCACHE_CPP2=yes
  matrix:
    - COVERAGE=ON

script:
  - mkdir build && cd build &&
    PATH="$HOME/bin:/usr/lib/ccache:$PATH" CC=gcc CXX=g++ cmake -DENABLE_INTEGRATED_TESTS=ON -DENABLE_UNIT_TESTS=ON ${COVERAGE:+-DENABLE_COVERAGE_BUILD=ON} .. &&
    make -j4 VERBOSE=1 && make test CTEST_OUTPUT_ON_FAILURE=1 && make install DESTDIR=$PWD

after_success:
  - if [[ ${COVERAGE} ]]; then cd .. && codecov --gcov-exec gcov; fi

cache:
  directories:
    - $HOME/.ccache

compiler:
  - gcc
