home_dir := env_var('HOME')
vpic := home_dir + "/vpic-kokkos/build/bin/vpic"

compile:
    {{vpic}} *.cxx

run:
    #!/usr/bin/env bash
    export DATADIR=/glade/derecho/scratch/$USER/pcai
    mkdir -p $DATADIR
    CUDIR="$(pwd)"
    # Copy input deck and change to data directory
    cd $DATADIR
    $CUDIR/*.Linux

clean:
	rm *.Linux
