# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the devel branch
on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Install deps
      run: sudo apt-get install gfortran openmpi-bin libopenmpi-dev
    - name: Checkout kokkos
      uses: actions/checkout@v2.2.0
      with:
        repository: kokkos/kokkos
        ref: 3.1.00
        path: kokkos
    - name: Build kokkos
      working-directory: kokkos
      run: |
        cmake -B build -DCMAKE_INSTALL_PREFIX=$HOME/kokkos -DKokkos_CXX_STANDARD=14 -DKokkos_ENABLE_${{ matrix.backend }}=ON
        cmake --build build --parallel 2
        cmake --install build
    - uses: actions/checkout@v2
    - name: configure
      run: cmake -B build -DCMAKE_PREFIX_PATH="$HOME/kokkos"
    - name: make
      run: cmake --build build
    - name: make check
      run: cmake --build build --target check
